In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.12.0'

In [4]:
data = pd.read_csv('Churn_Modelling.csv')

In [5]:
x = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [7]:
x[:, 2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [11]:
ann = tf.keras.models.Sequential()

In [12]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [13]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [14]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [15]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [34]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3319 - accuracy: 0.8646
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3313 - accuracy: 0.8665
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3320 - accuracy: 0.8643
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3315 - accuracy: 0.8644
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3319 - accuracy: 0.8650
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3317 - accuracy: 0.8658
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3315 - accuracy: 0.8645
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3315 - accuracy: 0.8643
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3316 - accuracy: 0.8654
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3316 - accura

In [35]:
# new client
new_client = [[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]

In [36]:
np.array(new_client)

array([[    1,     0,     0,   600,     1,    40,     3, 60000,     2,
            1,     1, 50000]])

In [37]:
new_client_sc = sc.transform(new_client)

In [38]:
print(ann.predict(new_client_sc))

1/1 [==============================] - 0s 45ms/step
[[0.03206863]]


In [43]:
y_pred = ann.predict(x_test)
y_pred = y_pred > 0.5

63/63 [==============================] - 0s 2ms/step


In [45]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1512   83]
 [ 199  206]]


0.859